name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: mkdir build; cd build; cmake ..
    - name: make
      run: cd build; make -j
    - name: make test
      run: cd build; make test
